### ISSUE TITLE
Long build times up to 30 minutes

### ISSUE THREAD

**Issue by wbmd-dho** [Sage-Bionetworks/BridgeAppSDK#173]
When we perform a clean build it takes up to 30 minutes to compile.  This seems to be caused by a run script inside the openssl.xcodeproj that runs "build-libssl.sh"

30 minutes is a very long time.  Is there a way around this?

On our end we have found some temporary remedies:
1) Avoid cleaning 
2) Modifying the build-libssl.sh to build only some and not all architectures
3) Using a precompiled universal framework for openssl

Number 1 is quite fleeting and we often need to clean build our project, thus we must endure another 30 minutes.
Number 2 is something we would like to avoid doing
Number 3 is the best solution we have found so far, but it requires modifying your project settings.

Is there a solution that you are using to avoid this problem?
Can you use a static library version of openssl to avoid calling "build-libssl.sh"

Please consult.

**Comment by Erin-Mounts** [comment]
The BridgeSDK project pre-builds universal binaries for libssl and libcrypto, and builds the openssl static library quickly from these. If you do a normal Clean from the Product menu in Xcode, it won't need to rebuild these once it has built them the first time for a given build configuration (e.g. Debug vs Release).

The only time these will need to be rebuilt is if you delete the pre-built binaries either by holding the Option key while opening the Product menu and selecting Clean Build Folder...,  or by deleting the Derived Data folder for the project. Or, of course, when doing an Archive build, because that builds everything from scratch every time.

**Comment by wbmd-dho** [comment]
"The only time these will need to be rebuilt is if you delete the pre-built binaries either by holding the Option key..."

This is untrue.  If Xcode detects significant changes it will automatically delete the derived data.  This usually occurs when we update BridgeAppSDK.  

We have 5 people on our team and it becomes a pain point for each and everybody to need to endure 30 minutes.  That time adds up.

We often need to test on multiple simulators and on devices; while some will reuse the same things in the derived data, more often then not, Xcode decides to rebuild libssl, lib crypto, and openssl.  

We also use Jenkins to make builds.  It builds it from scratch which means we have to wait an awfully  long time.

For these reasons, we would prefer an alternative.  

Currently you have an openssl.xcodeproj that builds the universal binaries for libssl and libcrypto then produces a static library.  I believe it may be better to just distribute the static library so we don't need to recreate it on our end.  So instead of a parent Xcode project referencing the openssl.xcodeproj, it could reference the static library and therefore eliminate the 30 minute build time from our end.

What are your thoughts on this?

**Comment by Erin-Mounts** [comment]
Honestly, I haven't seen Xcode doing this every time I update BridgeAppSDK. That might have been an unusual circumstance due to recently having moved OpenSSL from being a framework embedded in the app to being a static library linked by BridgeSDK. That doesn't change that it's a huge pain when it does need to rebuild openssl from scratch. This has been an issue I've had on my back burner for a while.

The only reason it's being built as a subproject instead of building the static library separately and linking that into BridgeSDK is actually outdated--it needed versions of the library with and without the simulator binaries based on the build configuration, so we could run in Simulator but wouldn't try to submit an app with simulator binaries to the App Store. But now with the App Store rebuilding everything from bitcode, that's no longer an issue. If you want to set it up that way--build a static library with all the binaries, put it in the project folder, and link the BridgeSDK target to that--and then do a pull request with those changes back to our fork, feel free to go for it; otherwise I can do it here once I get this https://github.com/Sage-Bionetworks/BridgeAppSDK/issues/172#issuecomment-278088338 taken care of, hopefully later today.

**Comment by wbmd-dho** [comment]
We would be very grateful.

**Comment by Erin-Mounts** [comment]
OK BridgeSDK is updated to use pre-built OpenSSL static libraries (it selects the correct one at build time), and BridgeAppSDK is updated to point at the new commit of BridgeSDK.

**Comment by wbmd-dho** [comment]
*standing ovation*

Thank you so much.  Our build times have been reduced by a factor of 10!

**Comment by Erin-Mounts** [comment]
Closing.
