### ISSUE TITLE
Request: Maintain consistent question font size when UI hints present

### ISSUE THREAD

**Issue by webmd-lsetch** [Sage-Bionetworks/BridgeAppSDK#183]
Issue: When I add UI hints to questions, the font size for the question triples in size. In one question, this is causing the list of drugs scroll space to become really small. See attached screen shots for differences in font sizes. 
![bp-question](https://cloud.githubusercontent.com/assets/25513532/22933090/6e673d7e-f298-11e6-8c66-23fc4ef7e973.png)
![weight-question](https://cloud.githubusercontent.com/assets/25513532/22933089/6e647ddc-f298-11e6-85db-5d7e2f4f1764.png)

**Comment by syoung-smallwisdom** [comment]
@webmd-lsetch 
BridgeAppSDK has been updated to make the placement of the prompt text consistent. Changing the font size requires changing ResearchKit and is outside the scope of what we have time to help you with. (sorry) In order to change font size, you will need to look at RK and submit an issue to that repo. Once you have a PR ready, if you ping me on the ResearchKit PR, I will review and merge into our fork. Thanks!
